import { IOpenAPIPropertyOptions, IOpenAPISchemaOptions, IOpenAPIParameter, IOpenAPISecuritySchema, SecuritySchemeType } from './openapi.interface';
export declare function ApiTags(...tags: string[]): MethodDecorator & ClassDecorator;
export declare function ApiExcludeController(disable?: boolean): ClassDecorator;
export declare function ApiSchema(options?: IOpenAPISchemaOptions): ClassDecorator;
export declare function ApiProperty(options?: IOpenAPIPropertyOptions, overrideExisting?: boolean): PropertyDecorator;
export declare function ApiPropertyOptional(options?: IOpenAPIPropertyOptions): PropertyDecorator;
export declare function ApiResponseProperty(options?: IOpenAPIPropertyOptions): PropertyDecorator;
export declare function ApiHideProperty(): PropertyDecorator;
export declare function ApiQuery(options: IOpenAPIParameter): MethodDecorator;
export declare function ApiHeader(options: IOpenAPIParameter): MethodDecorator;
export declare function ApiParam(options: IOpenAPIParameter): MethodDecorator;
export declare function ApiCookie(options: IOpenAPIParameter): MethodDecorator;
export declare function ApiSecurity(roles: string[] | string): MethodDecorator & ClassDecorator;
export declare function ApiSecuritySchema(options: IOpenAPISecuritySchema, type: SecuritySchemeType): MethodDecorator & ClassDecorator;
