name: TypeScript Tests

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'packages/**/*.ts'
      - 'src/**/*.ts'
      - 'package.json'
      - 'vitest.config.ts'
  pull_request:
    branches: [ '**' ]
    paths:
      - 'packages/**/*.ts'
      - 'src/**/*.ts'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 20.x ]

    steps:
    - uses: actions/checkout@v5

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run tests
      run: pnpm test -- --run

